[package]
name = "grpc-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "helloworld"
path = "src/main.rs"

[build-dependencies]
tonic-build = "0.12.3"

[dependencies]
prost = "0.13.4"
tokio = { version = "1.43.0", features = ["full"] }
tonic = "0.12.3"
